services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: honeypot
    networks:
      - lab_net
    volumes:
      - ./logs:/cowrie/cowrie-git/var/log/cowrie

  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - lab_net
    depends_on:
      - cowrie
    command: [ "python", "attack.py", "fast" ]

networks:
  lab_net:
    driver: bridge
    internal: true
